# Generated by Django 5.2.4 on 2025-08-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="bug",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
